apiVersion: v1
kind: Service
metadata:
  name: hello-gin-svc
  namespace: hello-gin
  labels:
    app: hello-gin
spec:
  type: ClusterIP
  selector:
    app: hello-gin
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP